services:
  - type: web
    name: flask-news-sentiment-app
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader vader_lexicon
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "{{random_secret_key}}"
    autoDeploy: true
